# -*- coding: utf-8 -*-
"""daa pertemuan 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZHlgT3P_LifEORMcgjPqIgF1a3O6mGZ
"""

import numpy as np

a = [1, 2, 3]
b = [4, 5, 6]


hasil = a + b

print(hasil)

nilai_siswa = np.array([85, 55, 40, 90])
print(nilai_siswa[3])

combined = a + b
result = sum(combined)
print(result)



nama = input("Masukkan nama Anda: ")
nim = input int("Masukkan NIM Anda: ")

print("Hello, World!")
print(f"Nama saya {nama}")
print(f"NIM saya {nim}")

if 5>2:
  print("Five is Greater than Two")

x = 4
x = "Sally"
print(x)

def getSecond(list):
  return list[1]

getSecond([1, 2, 3, 4, 5, 6, 8, 9])

def getFirst(list):
  return list[0]

getFirst([1, 2, 3, 4, 5, 6, 8, 9])

def getLast(list):
  size = len(list)
  print(size)
  return list[size-1]

getLast([1, 2, 3, 4, 5, 6, 8, 9])

def getSum(list):
  sum = 1
  for item in list:
      sum += item
  return sum

angka = [2, 3, 4]
print(getSum(angka))

def getKali(list):
    result = 1
    for number in list:
        result *= number
    return result

angka = [2, 3, 4]
print(getKali(angka))

def getBagi(list):
  sum = 1
  for item in list:
      sum /= item
  return sum

angka = [2, 3, 4]
print(getBagi(angka))

def getSum(himpunan):
    return sum(himpunan)

def divideSets(set1, set2):

    total_set1 = getSum(set1)
    total_set2 = getSum(set2)

    if total_set2 == 0:
        return "Tidak bisa membagi dengan nol"

    return total_set1 / total_set2

himpunan1 = {10, 20, 30}
himpunan2 = {5, 15}

hasil = divideSets(himpunan1, himpunan2)
print(f"Hasil pembagian: {hasil}")

def getSum(angka_set):
    return sum(angka_set)

def subtractSets(set1, set2):
    sum_set1 = getSum(set1)
    sum_set2 = getSum(set2)

    return sum_set1 - sum_set2

set1 = {3, 5, 8}
set2 = {2, 4}

hasil_pengurangan = subtractSets(set1, set2)
print(f"Hasil pengurangan: {hasil_pengurangan}")